---
title: "p8105_hw6_problem1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, cachedChunk, cache = TRUE}
library(flexdashboard)
library(tidyverse)
library(forcats)
library(plotly)
library(janitor)
library(tidyr)
library(dplyr)

ny_noaa = read_csv("../data/nynoaadat.zip") %>%
  clean_names %>%
  separate(date, into = c("year", "month","day"), sep = "-") %>%
  filter(year >= 2000) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Figure 1: General Trend of Precipitation

```{r, cachedChunk, cache = TRUE}
ny_noaa %>%
  select("year", "month","prcp") %>%
  na.omit() %>%
  mutate(month = as.numeric(month),
         prcp = as.numeric(prcp)) %>%
  group_by(year, month) %>%
  summarize(mean_prcp = mean(prcp)) %>%
  plot_ly(y = ~mean_prcp, x = ~month, color = ~year, type = "scatter", mode = "lines") %>%
    layout(title = "Annual Precipitation Trends")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, cache = TRUE}
ny_noaa %>%
  select("year", "tmin", "tmax") %>%
  na.omit() %>%
  group_by(year) %>%
  mutate(tmax = as.numeric((tmax)),
         tmin = as.numeric((tmin))) %>%
  summarize(mean_tmin = mean(tmin),  
          mean_tmax = mean(tmax)) %>%
  plot_ly(y = ~mean_tmin , x = ~mean_tmax , type = "scatter") %>%
    layout(title = "Mean Tmax & Tmin")

#for some reason, mode = "points" is giving you connected lines, have yet to trouble shoot that, color = ~"year" doesn't work either
#also heads up, idk if actually saving our figures and then printing them is a good idea, might not print well on flexdashboard
```


### Chart C

```{r}
ny_noaa %>%
  select("year", "month", "tmax") %>%
  na.omit() %>%
  mutate(tmax = as.numeric(tmax)) %>%
  group_by(year, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  plot_ly(y = ~mean_tmax, color = ~month, type = "box") %>%
    layout(title = "Average Maximum Temperatures for 2000-2010")
```

